global:
  domain_name: 24022020.xyz
  revision: main

argocd:
  namespace_name: argocd
  chart_version: 9.1.5
  exec:
    enabled: true

cloudflare:
  namespace_name: cloudflare
  chart_version: 0.3.2
  version: 2026.3.0

envoy:
  namespace_name: envoy
  chart_version: v1.7.2
