version: "3.9"

services:
  traefik:
    image: traefik:v3.6.16
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs/:/logs/
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`traefik.24022020.xyz`)"
      - "traefik.http.routers.api.service=api@internal"

  cloudflared:
    image: cloudflare/cloudflared:2026.3.0
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
    networks:
      - web
    depends_on:
      - traefik

networks:
  web:
    name: web
