---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: {{ .Values.argocd.namespace_name }}
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.argocd.namespace_name }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: {{ .Values.argocd.chart_version }}
    helm:
      values: |
        global:
          logging:
            format: json

        server:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi

        repoServer:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi

        applicationController:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi

        dex:
          enabled: false

        notifications:
          enabled: false

        applicationSet:
          enabled: false

        redis-ha:
          enabled: false

        redis:
          enabled: true
          resources:
            requests:
              cpu: 25m
              memory: 32Mi

        configs:
          cm:
            create: true
            exec.enabled: true
